name: test-release

on: workflow_call

jobs:
  tox-tests:
    uses: ./.github/workflows/tox-tests.yml

  code-quality-release-pypi:
    needs: tox-tests
    uses: ./.github/workflows/send-to-pypi.yml
    with:
      username: __token__
    secrets:
      test_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
      token: ${{ secrets.PYPI_API_TOKEN }}